sudo: required

addons:
  chrome: stable

language: node_js

cache: yarn

node_js:
  - "6"

before_install:
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8

install:
  - npm install

script:
  - npm run test:cov

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
